---
services:
  clash:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7681:7681
    volumes:
      - .:/usr/src/clash
    stdin_open: true
    tty: true
    environment:
      - TZ=America/Denver
    restart: unless-stopped
